FROM datmo/opencv:gpu-py27

MAINTAINER Datmo devs <dev@datmo.com>

ARG PYTORCH_VERSION=0.4.0
ARG PYTORCH_CUDA_VERSION=91

# Install pytorch
RUN pip install http://download.pytorch.org/whl/cu${PYTORCH_CUDA_VERSION}/torch-${PYTORCH_VERSION}-cp27-cp27mu-linux_x86_64.whl
RUN pip install torchvision